# Generated by Django 5.0.8 on 2025-03-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_study_time', models.FloatField()),
                ('num_breaks', models.IntegerField()),
                ('break_duration', models.FloatField()),
                ('leisure_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.FloatField()),
                ('importance', models.FloatField()),
                ('min_time', models.FloatField()),
            ],
        ),
    ]
