# Generated by Django 5.1.2 on 2025-04-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_studytopic_name_studysubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytopic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='StudySubject',
        ),
    ]
