# Generated by Django 5.1.2 on 2025-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_studypreferences_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypreferences',
            name='break_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='leisure_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='num_breaks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='total_study_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
