# Generated by Django 5.1.2 on 2025-04-10 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_studypreferences_break_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyTopic',
        ),
        migrations.AddField(
            model_name='studypreferences',
            name='priorities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studypreferences',
            name='session_length',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='studypreferences',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='studypreferences',
            name='study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='break_duration',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='leisure_time',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='num_breaks',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studypreferences',
            name='total_study_time',
            field=models.FloatField(default=8),
        ),
    ]
